name: Get Python versions
on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  get-new-python-versions:
    uses: HarithaVattikuti/versions-package-tools/.github/workflows/get-new-tool-versions.yml@TestPatch
    with:
      tool-name: "Python"
      image-url: "https://avatars.githubusercontent.com/u/1525981?s=200&v=4"
    secrets: inherit
